version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
      dev-dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@vue/runtime-dom'
          - 'vue'
          - 'typescript'
