name: Setup
description: Setup node and install dependencies
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    - uses: bahmutov/npm-install@v1
